const START_LAT_LNG = {
  lat: 35.672,
  lng: 139.78,
};
const LAT_LNG_PRECISSION = 5;
const MAIN_PIN_ICON_HEIGHT = 32;
const PIN_ICON_HEIGHT = 24;

export{
  START_LAT_LNG,
  LAT_LNG_PRECISSION,
  MAIN_PIN_ICON_HEIGHT,
  PIN_ICON_HEIGHT
};
